import classical_hypergeometric_functions_2f1_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace classical_hypergeometric_functions_2f1_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end classical_hypergeometric_functions_2f1_foundation_canonical_lane_mathlib
end HautevilleHouse
